/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Models.*;
/**
 *
 * @author Walker
 */
public class SecretaryGUI extends javax.swing.JFrame {

    /**
     * Creates new form PatientGUI
     */
    public SecretaryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApprovePatientAccounts = new javax.swing.JButton();
        btnViewAppointmentRequests = new javax.swing.JButton();
        btnCreateAppointment = new javax.swing.JButton();
        btnRemovePatient = new javax.swing.JButton();
        btnGiveMedicines = new javax.swing.JButton();
        lblSecretary = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPatient = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnApprovePatientAccounts.setText("Approve Patient Accounts");
        btnApprovePatientAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovePatientAccountsActionPerformed(evt);
            }
        });

        btnViewAppointmentRequests.setText("View Appointment Requests");
        btnViewAppointmentRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAppointmentRequestsActionPerformed(evt);
            }
        });

        btnCreateAppointment.setText("Create Appointment ");
        btnCreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppointmentActionPerformed(evt);
            }
        });

        btnRemovePatient.setText("Remove Patient");
        btnRemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePatientActionPerformed(evt);
            }
        });

        btnGiveMedicines.setText("Give Medicines");
        btnGiveMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveMedicinesActionPerformed(evt);
            }
        });

        lblSecretary.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSecretary.setText("Secretary");

        txtAreaPatient.setColumns(20);
        txtAreaPatient.setRows(5);
        jScrollPane1.setViewportView(txtAreaPatient);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addContainerGap(576, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemovePatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(btnGiveMedicines, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(btnViewAppointmentRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(btnApprovePatientAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSecretary, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSecretary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApprovePatientAccounts)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewAppointmentRequests)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateAppointment)
                        .addGap(18, 18, 18)
                        .addComponent(btnGiveMedicines)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemovePatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePatientActionPerformed
        SecretaryRemovePatientGUI sGo = new SecretaryRemovePatientGUI();
        SecretaryGUI sLeave = new SecretaryGUI();
        sGo.setVisible(true);
        sLeave.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnRemovePatientActionPerformed

    private void btnCreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppointmentActionPerformed
        SecretaryCreateAppointmentGUI sGo = new SecretaryCreateAppointmentGUI();
        SecretaryGUI sLeave = new SecretaryGUI();
        sGo.setVisible(true);
        sLeave.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCreateAppointmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginGUI loginGUIInstance = new LoginGUI();
        SecretaryGUI secretaryGUIInstance = new SecretaryGUI();
        loginGUIInstance.setVisible(true);
        secretaryGUIInstance.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnApprovePatientAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovePatientAccountsActionPerformed
        SecretaryApprovePatientsGUI sGo = new SecretaryApprovePatientsGUI();
        SecretaryGUI sLeave = new SecretaryGUI();
        sGo.setVisible(true);
        sLeave.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnApprovePatientAccountsActionPerformed

    private void btnViewAppointmentRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAppointmentRequestsActionPerformed
        SecretaryViewAppointmentRequestsGUI sGo = new SecretaryViewAppointmentRequestsGUI();
        SecretaryGUI sLeave = new SecretaryGUI();
        sGo.setVisible(true);
        sLeave.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnViewAppointmentRequestsActionPerformed

    private void btnGiveMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveMedicinesActionPerformed
        SecretaryGiveMedicinesGUI sGo = new SecretaryGiveMedicinesGUI();
        SecretaryGUI sLeave = new SecretaryGUI();
        sGo.setVisible(true);
        sLeave.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnGiveMedicinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovePatientAccounts;
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnGiveMedicines;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemovePatient;
    private javax.swing.JButton btnViewAppointmentRequests;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSecretary;
    private javax.swing.JTextArea txtAreaPatient;
    // End of variables declaration//GEN-END:variables
}
